Update extractor-trim.js
axa-group/nlp.js pull request #1278
Opened 2023-02-11 04:37 UTC by DK013

fix for error: exec is not a function

# Pull Request Template

## PR Checklist

- [✓ ] I have run `npm test` locally and all tests are passing.
- [✓ ] [(https://github.com/axa-group/nlp.js/issues/463)]

## PR Description

#463
In production if someone tries to load model nlp/json file instead of trainning from corpus, the match between function in extractor-trim.js under @nlpjs/ner package throws error: `TypeError: condition.regex.exec is not a function`  
The reason of this error is when saved in a json file the generated regex is saved as a string instead of regex data type.

FIX:  
- check if `condition.regex` is a string  
- modify the string to be used in `RegExp` function so it doesn't escape characters unneccesserily  
- convert `condition.regex` to regex  
- in training mode if `condition.regex` is already regex, the program executes as it should normally

2023-02-11 10:12 UTC, Apollon77 requested changes
Beside the minimal code reveiw stuff I would more ask if not the place where we ADD the condition is the best place to do this conversion **once** instead of here maaaany times because it is done on every match try ....

2023-02-11 10:12 UTC, Apollon77 commented on packages/ner/src/extractor-trim.js
> +    if(typeof condition.regex === 'string') {
Please stick to code style :-)

```suggestion
    if (typeof condition.regex === 'string') {
```

2023-02-11 10:12 UTC, Apollon77 commented on packages/ner/src/extractor-trim.js
> +      if(condition.regex.startsWith('/'))
```suggestion
      if (condition.regex.startsWith('/'))
```

2023-02-16 04:41 UTC, DK013 commented
> Beside the minimal code reveiw stuff I would more ask if not the place where we ADD the condition is the best place to do this conversion **once** instead of here maaaany times because it is done on every match try ....

I am aware of that fact. However I'm not sure of the source where the `condition` variable is populated. And I don't think placing the conversion where `matchBetween` function is called will change the urrent outcome. If you can just guide me to where the variable is populated I can simple move the code there so the conversion only happens once.

2023-02-16 07:44 UTC, Apollon77 commented
The code how to add a regex rule is here https://github.com/axa-group/nlp.js/blob/032d4093e44516bc3e1a26d880d1c9fb587e1181/packages/ner/src/ner.js#L239-L247

Adding a Between condition is done in https://github.com/axa-group/nlp.js/blob/032d4093e44516bc3e1a26d880d1c9fb587e1181/packages/ner/src/ner.js#L269

and basically in the end addRukeis used to add new rules

If your case is more the "restore from json" then https://github.com/axa-group/nlp.js/blob/032d4093e44516bc3e1a26d880d1c9fb587e1181/packages/ner/src/ner.js#L511 might be the place to check if all is initialized correctly there

2023-05-19 04:29 UTC, AndersDJohnson commented
Hi @DK013 @Apollon77 this might be fixed by https://github.com/axa-group/nlp.js/pull/1314

2023-05-25 10:56 UTC, Apollon77 commented
@ericzon I would close this PR in favor of #1314!!

2023-05-25 11:20 UTC, ericzon commented
As @Apollon77  suggested, closed in favor of #1314

2023-05-25 11:20 UTC, closed without merging